version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: renzhin/486_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
  gateway:
    image: renzhin/486_gateway
    env_file: .env
    ports:
      - ${WEB_PORT}:80
    volumes:
      - static:/static
      - media:/media
