# Generated by Django 3.2.16 on 2024-04-02 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpus', '0003_auto_20240319_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu',
            options={'ordering': ('-purchase_date', '-created_at'), 'verbose_name': 'процессор', 'verbose_name_plural': 'Процессоры'},
        ),
    ]
