# Generated by Django 3.2.16 on 2024-03-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpus', '0004_auto_20240309_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='in_interesting',
            field=models.BooleanField(default=False, help_text='Снимите галочку, чтобы скрыть с главной.', verbose_name='В интересном'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть публикацию.', verbose_name='Опубликовано'),
        ),
    ]
