# Generated by Django 3.2.16 on 2024-04-18 16:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpus', '0004_alter_cpu_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='catalog_number',
            field=models.CharField(blank=True, max_length=4, verbose_name='номер в коллекции'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть публикацию.', verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='purchase_price',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='стоимость покупки'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='rarity',
            field=models.CharField(choices=[('NN', 'Не задано'), ('CM', 'Частый'), ('UN', 'Нечастый'), ('RR', 'Редкий'), ('ER', 'Очень редкий')], default='NN', max_length=128, verbose_name='редкость'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='sale_price',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='стоимость продажи'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpus', to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='work_status',
            field=models.CharField(choices=[('NT', 'Непроверенный'), ('WK', 'Рабочий'), ('DF', 'Неисправен'), ('OC', 'Разогнан')], default='NT', max_length=128, verbose_name='статус'),
        ),
    ]
