# Generated by Django 3.2.16 on 2024-05-22 05:05

import cpus.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpus', '0005_auto_20240418_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='purchase_date',
            field=models.DateField(validators=[cpus.validators.real_date], verbose_name='дата покупки'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='sale_date',
            field=models.DateField(blank=True, null=True, validators=[cpus.validators.real_date], verbose_name='дата продажи'),
        ),
    ]
