# Generated by Django 3.2.16 on 2024-03-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpus', '0005_auto_20240317_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='hidden_description',
            field=models.TextField(blank=True, null=True, verbose_name='Скрытое описание'),
        ),
    ]
