# Generated by Django 3.2.16 on 2024-04-02 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_modifieduser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifieduser',
            name='registrated_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата регистрации'),
            preserve_default=False,
        ),
    ]
